
development:
  adapter: postgresql
  host: localhost
  database: tc_rails_development
  username: postgres
  password: postgres
  encoding: unicode
          
test:
  adapter: postgresql
  host: localhost
  database: tc_rails_test
  username: postgres
  password: postgres
  encoding: unicode

production:
  adapter: postgresql
  host: localhost
  database: tc_rails_production
  username: postgres
  password: postgres
  encoding: unicode